import React, { useState, useEffect } from 'react';
import { api } from '../../api';
import Sidebar from '../../components/Sidebar';
import { toast } from '../../utils/toast';
import {
  Megaphone, Sparkles, Send, BarChart3, HelpCircle,
  Copy, Check, RefreshCw, Layers, TrendingUp, Users, Inbox
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, Legend
} from 'recharts';

export default function PromotionAi() {
  const [topic, setTopic] = useState('');
  const [channel, setChannel] = useState('email');
  const [audience, setAudience] = useState('all hackers');
  const [abTest, setAbTest] = useState(true);
  const [title, setTitle] = useState('');

  const [generating, setGenerating] = useState(false);
  const [launching, setLaunching] = useState(false);
  const [loadingHistory, setLoadingHistory] = useState(true);

  const [generatedA, setGeneratedA] = useState('');
  const [generatedB, setGeneratedB] = useState('');
  const [generatedSubject, setGeneratedSubject] = useState('');
  const [hasGenerated, setHasGenerated] = useState(false);

  const [campaigns, setCampaigns] = useState([]);
  const [copied, setCopied] = useState('');

  const fetchCampaigns = async () => {
    setLoadingHistory(true);
    try {
      const res = await api.get('/promotions/performance');
      setCampaigns(res || []);
    } catch (err) {
      toast.error('Failed to load campaign performance logs.');
    } finally {
      setLoadingHistory(false);
    }
  };

  useEffect(() => {
    fetchCampaigns();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!topic.trim()) {
      return toast.warning('Please enter a topic or theme.');
    }
    setGenerating(true);
    setHasGenerated(false);
    try {
      const res = await api.post('/promotions/generate', {
        topic, channel, audience, abTest
      });
      setGeneratedA(res.contentA || '');
      setGeneratedB(res.contentB || '');
      setGeneratedSubject(res.subject || '');
      setHasGenerated(true);
      toast.success('Promotional content generated by AI!');
    } catch (err) {
      toast.error(err.message || 'Generation failed.');
    } finally {
      setGenerating(false);
    }
  };

  const handleLaunch = async (e) => {
    e.preventDefault();
    if (!title.trim()) {
      return toast.warning('Please enter a Campaign Name.');
    }
    setLaunching(true);
    try {
      await api.post('/promotions/ab-test', {
        title,
        channel,
        subject: generatedSubject,
        contentA: generatedA,
        contentB: generatedB,
        abTestEnabled: abTest,
        audience
      });
      toast.success('Campaign launched successfully! Performance metrics simulated.');
      setTitle('');
      setTopic('');
      setHasGenerated(false);
      fetchCampaigns();
    } catch (err) {
      toast.error(err.message || 'Failed to launch campaign.');
    } finally {
      setLaunching(false);
    }
  };

  const handleCopy = (text, key) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(''), 2000);
    toast.success('Copied to clipboard!');
  };

  return (
    <div className="app-shell" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
      <Sidebar />
      <main className="main-content">
        <div className="page-header">
          <div>
            <h1 className="page-title flex items-center gap-2">
              <Megaphone className="text-orange-500" size={24} />
              Promotion AI & Growth Engine
            </h1>
            <p className="page-subtitle">
              Generate high-conversion promotional content for multiple marketing channels and run automated A/B performance tests.
            </p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.2fr)', gap: 24, marginBottom: 24 }}>
          {/* LEFT: Promotion Generator */}
          <div className="card">
            <h3 className="flex items-center gap-1.5 font-bold mb-4 text-[15px]">
              <Sparkles size={16} className="text-orange-500" />
              AI Copywriter Setup
            </h3>
            <form onSubmit={handleGenerate} className="space-y-4">
              <div className="form-group">
                <label className="form-label">Theme or Core Subject</label>
                <textarea
                  className="form-textarea"
                  value={topic}
                  onChange={e => setTopic(e.target.value)}
                  placeholder="e.g. Build decentralized web apps or AI tools to optimize college schedules. Mention prizes of $2000."
                  rows={4}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">Target Channel</label>
                <select
                  className="form-select"
                  value={channel}
                  onChange={e => setChannel(e.target.value)}
                >
                  <option value="email">Email Campaign</option>
                  <option value="slack">Slack / Discord Announcement</option>
                  <option value="twitter">X (formerly Twitter)</option>
                  <option value="linkedin">LinkedIn Post</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Target Audience Segment</label>
                <input
                  type="text"
                  className="form-input"
                  value={audience}
                  onChange={e => setAudience(e.target.value)}
                  placeholder="e.g. React developers, students, experienced engineers"
                />
              </div>

              <div className="flex items-center gap-2 py-1">
                <input
                  type="checkbox"
                  id="abTest"
                  checked={abTest}
                  onChange={e => setAbTest(e.target.checked)}
                  style={{ width: 16, height: 16, cursor: 'pointer' }}
                />
                <label htmlFor="abTest" style={{ fontSize: 13, fontWeight: 500, cursor: 'pointer', userSelect: 'none' }}>
                  Enable A/B Split Testing (Generates 2 variants)
                </label>
              </div>

              <button type="submit" className="btn btn-primary btn-full flex items-center justify-center gap-1.5" disabled={generating}>
                {generating ? (
                  <>
                    <RefreshCw className="animate-spin" size={15} />
                    Generating Copy...
                  </>
                ) : (
                  <>
                    <Sparkles size={15} />
                    Generate Marketing Copy
                  </>
                )}
              </button>
            </form>
          </div>

          {/* RIGHT: Generated Outputs */}
          <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
            <h3 className="font-bold mb-4 text-[15px] flex items-center gap-1.5">
              <Layers size={16} />
              AI Copywriter Outputs
            </h3>

            {!hasGenerated ? (
              <div style={{ margin: 'auto', textAlign: 'center', color: 'var(--text-muted)', padding: 40 }}>
                <Inbox size={32} style={{ margin: 'auto', marginBottom: 12, opacity: 0.5 }} />
                <p style={{ fontSize: 13 }}>Setup parameters on the left and click generate to generate conversion-optimized templates.</p>
              </div>
            ) : (
              <div className="space-y-4 flex-1 overflow-y-auto pr-1">
                {channel === 'email' && generatedSubject && (
                  <div className="form-group">
                    <label className="form-label flex-between">
                      <span>Generated Subject Line</span>
                      <button onClick={() => handleCopy(generatedSubject, 'subject')} className="btn btn-muted flex items-center gap-1 text-[11px]" style={{ padding: '2px 6px' }}>
                        {copied === 'subject' ? <Check size={10} /> : <Copy size={10} />} Copy
                      </button>
                    </label>
                    <input type="text" className="form-input font-bold" value={generatedSubject} readOnly />
                  </div>
                )}

                <div className="form-group">
                  <label className="form-label flex-between">
                    <span>{abTest ? 'Variant A (Standard Hook)' : 'Generated Copy'}</span>
                    <button onClick={() => handleCopy(generatedA, 'varA')} className="btn btn-muted flex items-center gap-1 text-[11px]" style={{ padding: '2px 6px' }}>
                      {copied === 'varA' ? <Check size={10} /> : <Copy size={10} />} Copy
                    </button>
                  </label>
                  <textarea className="form-textarea font-mono text-[12px] bg-stone-950 text-stone-100" value={generatedA} rows={abTest ? 5 : 10} readOnly />
                </div>

                {abTest && (
                  <div className="form-group">
                    <label className="form-label flex-between">
                      <span>Variant B (Alternative Hook)</span>
                      <button onClick={() => handleCopy(generatedB, 'varB')} className="btn btn-muted flex items-center gap-1 text-[11px]" style={{ padding: '2px 6px' }}>
                        {copied === 'varB' ? <Check size={10} /> : <Copy size={10} />} Copy
                      </button>
                    </label>
                    <textarea className="form-textarea font-mono text-[12px] bg-stone-950 text-stone-100" value={generatedB} rows={5} readOnly />
                  </div>
                )}

                <div style={{ height: 1, background: 'var(--border)', margin: '16px 0' }} />

                <form onSubmit={handleLaunch} className="space-y-3">
                  <div className="form-group">
                    <label className="form-label">Campaign Name / Identifier</label>
                    <input
                      type="text"
                      className="form-input"
                      value={title}
                      onChange={e => setTitle(e.target.value)}
                      placeholder="e.g. June Hackathon Launch Campaign"
                      required
                    />
                  </div>
                  <button type="submit" className="btn btn-secondary btn-full flex items-center justify-center gap-1.5" disabled={launching}>
                    <Send size={14} />
                    {launching ? 'Launching Campaign...' : 'Save & Launch Campaign'}
                  </button>
                </form>
              </div>
            )}
          </div>
        </div>

        {/* Analytics and History */}
        <div className="card">
          <h3 className="font-bold mb-6 text-[15px] flex items-center gap-1.5">
            <BarChart3 size={16} />
            Historical Campaign performance
          </h3>

          {loadingHistory ? (
            <div style={{ padding: 40, textAlign: 'center' }}><div className="spinner" style={{ margin: 'auto' }} /></div>
          ) : campaigns.length === 0 ? (
            <div style={{ padding: 40, textAlign: 'center', color: 'var(--text-muted)' }}>
              No active marketing campaigns found. Launch one above!
            </div>
          ) : (
            <div className="space-y-8">
              {campaigns.map(c => {
                const ctrA = c.metrics.sent > 0 ? ((c.metrics.clicksA / c.metrics.sent) * 100).toFixed(1) : 0;
                const ctrB = c.metrics.sent > 0 ? ((c.metrics.clicksB / c.metrics.sent) * 100).toFixed(1) : 0;
                const openA = c.metrics.sent > 0 ? ((c.metrics.opensA / c.metrics.sent) * 100).toFixed(1) : 0;
                const openB = c.metrics.sent > 0 ? ((c.metrics.opensB / c.metrics.sent) * 100).toFixed(1) : 0;

                // Recharts data
                const chartData = [
                  { name: 'Variant A', Clicks: c.metrics.clicksA, Opens: c.metrics.opensA },
                ];
                if (c.abTestEnabled) {
                  chartData.push({ name: 'Variant B', Clicks: c.metrics.clicksB, Opens: c.metrics.opensB });
                }

                const winner = Number(ctrB) > Number(ctrA) ? 'Variant B' : 'Variant A';

                return (
                  <div key={c._id} style={{ border: '1px solid var(--border)', borderRadius: 12, padding: 20 }}>
                    <div className="flex-between" style={{ marginBottom: 16 }}>
                      <div>
                        <h4 style={{ fontSize: 15, fontWeight: 700 }}>{c.title}</h4>
                        <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                          Channel: <span style={{ textTransform: 'capitalize' }}>{c.channel}</span> | Audience: {c.audience} | Sent: {c.metrics.sent}
                        </p>
                      </div>
                      <span className="badge badge-success flex items-center gap-1 font-bold">
                        <TrendingUp size={11} /> Active
                      </span>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 0.8fr', gap: 24, alignItems: 'center' }}>
                      {/* Chart */}
                      <div style={{ height: 180 }}>
                        <ResponsiveContainer width="100%" height="100%">
                          <BarChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" />
                            <XAxis dataKey="name" stroke="var(--text-muted)" fontSize={12} />
                            <YAxis stroke="var(--text-muted)" fontSize={12} />
                            <Tooltip contentStyle={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }} />
                            <Legend />
                            <Bar dataKey="Opens" fill="rgba(234, 88, 12, 0.7)" radius={[4, 4, 0, 0]} />
                            <Bar dataKey="Clicks" fill="rgba(16, 185, 129, 0.7)" radius={[4, 4, 0, 0]} />
                          </BarChart>
                        </ResponsiveContainer>
                      </div>

                      {/* Performance card */}
                      <div style={{ background: 'var(--bg-elevated)', borderRadius: 8, padding: 16 }}>
                        <h5 style={{ fontSize: 12, fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 12 }}>
                          Performance Breakdown
                        </h5>
                        <div className="space-y-2" style={{ fontSize: 13 }}>
                          <div className="flex-between">
                            <span>Variant A CTR:</span>
                            <span style={{ fontWeight: 700 }}>{ctrA}% ({c.metrics.clicksA} clicks)</span>
                          </div>
                          {c.abTestEnabled && (
                            <>
                              <div className="flex-between">
                                <span>Variant B CTR:</span>
                                <span style={{ fontWeight: 700 }}>{ctrB}% ({c.metrics.clicksB} clicks)</span>
                              </div>
                              <div className="flex-between" style={{ borderTop: '1px solid var(--border)', paddingTop: 8, marginTop: 8 }}>
                                <span>Winner Hook:</span>
                                <span className="text-emerald-500 font-bold">{winner}</span>
                              </div>
                            </>
                          )}
                          <div className="flex-between" style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                            <span>Total Impressions:</span>
                            <span>{c.metrics.impressions}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
